-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.aseguradora
(
    id_aseguradora serial NOT NULL,
    nombre_aseguradora character varying(20) COLLATE pg_catalog."default",
    id_tipo_vehiculo text COLLATE pg_catalog."default",
    fecha_contrato numeric(10, 0),
    CONSTRAINT aseguradora_pkey PRIMARY KEY (id_aseguradora)
);

CREATE TABLE IF NOT EXISTS public.caracteristicas_vehiculo
(
    id_caracteristicas_vehiculos serial NOT NULL,
    marca character varying(20) COLLATE pg_catalog."default",
    modelo character varying(20) COLLATE pg_catalog."default",
    numero_serie character varying(30) COLLATE pg_catalog."default",
    transmision character varying(20) COLLATE pg_catalog."default",
    color character varying(20) COLLATE pg_catalog."default",
    id_aseguradora integer,
    CONSTRAINT caracteristicas_vehiculo_pkey PRIMARY KEY (id_caracteristicas_vehiculos)
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    id_cliente serial NOT NULL,
    apellido_paterno character varying(20) COLLATE pg_catalog."default",
    apellido_materno character varying(20) COLLATE pg_catalog."default",
    nombre character varying(20) COLLATE pg_catalog."default",
    sexo character varying(20) COLLATE pg_catalog."default",
    curp character varying(30) COLLATE pg_catalog."default",
    rfc character varying(20) COLLATE pg_catalog."default",
    numero_telefonico character varying(20) COLLATE pg_catalog."default",
    correo_electronico character varying(30) COLLATE pg_catalog."default",
    id_direccion_cliente integer,
    id_caracteristicas_vehiculo integer,
    CONSTRAINT cliente_pkey PRIMARY KEY (id_cliente)
);

CREATE TABLE IF NOT EXISTS public.direccion_cliente
(
    id_direccion_cliente serial NOT NULL,
    calle character varying(30) COLLATE pg_catalog."default",
    colonia character varying(30) COLLATE pg_catalog."default",
    "c.p." character varying(30) COLLATE pg_catalog."default",
    municipio character varying(30) COLLATE pg_catalog."default",
    estado character varying COLLATE pg_catalog."default",
    CONSTRAINT direccion_cliente_pkey PRIMARY KEY (id_direccion_cliente)
);

ALTER TABLE IF EXISTS public.caracteristicas_vehiculo
    ADD CONSTRAINT caracteristicas_vehiculo_id_aseguradora_fkey FOREIGN KEY (id_aseguradora)
    REFERENCES public.aseguradora (id_aseguradora) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cliente
    ADD CONSTRAINT cliente_id_direccion_cliente_fkey FOREIGN KEY (id_direccion_cliente)
    REFERENCES public.direccion_cliente (id_direccion_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;